language: scala

scala:
    - 2.11.8

script:
    - sbt test
    - sbt prod/dist

after_success:
    - mv dist anki-iframe-viewer
    - zip -r anki-iframe-viewer.zip anki-iframe-viewer

branches:
    except:
        - master

deploy:
    provider: releases
    api_key:
        secure: "SUy+v2gXMPRdo+ngWLz36MI+g48Xoa4Bul7PwJlRB8qnOnD5WbyTewcFEH6DSPHqDDEmwFjkhJStn5TBkP3klWTDT1ZZhTTtSiNeMaFp2s4K0ARNjnX/4QK+6mh5KZ0cqHfP4MONKzcB3BbbQP1EeodtiJ4DPRSR//WY2X9aBKgY3aXdaSUxFzrU1tZJb3a5at7Z2ZGwcvaeGk7CFHIg+UQFtgfnTR5/ijr9Ikk0cgOLgTF3kwFdDwfmk9PauEo4BwInIG/k5bI3D4dS2iGjkOZ+wZk2wIAmjXk1DuGrDm6vlkZ1xQR4vSo4sWgRoB2lzJEUKfpIYMBuQSWPY5YWEC2TSkJUEL/s7uw5G2qwNxTjDZAi2qDdj+vsPjeb/NjGt0Lv5GTz62vpbOhFjJs28z4Trs39yOaquQMz/mWJ3n8XvRBTPdqeXFjcaRCbsDN4R7f2ZagYuappxd/RkELGxmNIK4pVwk/VWP0xnGjgcn0iHkbBrBVlR9weZNDG7P4GJ/5PFcjBfrng44iBRQdhZySXkz5qE7kIiA1I7Pt8wKTZIwsj6Mey1X5/nWy5+NpHQ/rdTpkP9zeuB4iR0IRMLpgD42+DIGnf7QVmhgpDERIhqonf9Phi31lmSHIiWfVdQYFCRqK+WNis/dZvH/Ykc0Qb1lii1h8F2hszMOu5OrA="
    file:
        - anki-iframe-viewer.zip
    skip_cleanup: true
    on:
        repo: rubyu/anki-iframe-viewer
        tags: true
        all_branches: true
