language: scala

scala:
    - 2.11.8

script:
    - sbt prod/dist

after_success:
    - mv dist anki-iframe-viewer
    - zip -r anki-iframe-viewer.zip anki-iframe-viewer

addons:
    artifacts: true

branches:
    except:
        - master

deploy:
    provider: releases
    api_key: "NxyCYegOqIrmRBKINSqhthc7BTM4ZAE9/lZ7rumiZe8inntJ5Iqn+zJ0R9hErtDoB0ep1kAdunj6RQVVB+H/B+jivRE5GzPm9mDlMER0vd3QeSijmUJ70qPgVzhHAHfL1rGr3Z/WyDsaMzUE/IW8TGW9O7jxakxqe9mUO/iJkekdAhVvpqXYZvP0FgOP5gkKa1jnmQYkbCKIOXeZ3QGiaady5c8glqTLqw7Tn0yBcBGQT4c7LBgTuXKnufq8hBld4eYCwlnLmBS+MPUPThHi9kR6IPQ1AW1d/O9qxfMNGxWlLkUZiumfibzFTGGnihoP4r21Psh/rM6UZR8WGWIrOZDHHJO+13/h//jxcZpiFWag0JuWZeWtalurcA69jK+vY7m6H5KyVlYRVdpT8LfSsQIPTWT9Rlmnxgw31hfCCItu85WV3cKLL3+2/EwYTLTQvmQUsY7fwrT788LimGHg/mIxOvIjOkir3rEiY0O6eiynAgyhxaYVOo0AgjTPfyr9uxegcrRTfGdl9rzX24uuNrhVA603pvtOkk2V0RpqLq9o6lJLg2o3eacbXehpvwa9qoiuKeBZo9yI9RdWfr+bNfAzBmexRA6VHs1pRvgZnW/TxZCSgE4XGMRDfmc1ntFvNdXhNO9ubI+O0jGGY6BEWSE/pj7f/db/fJKWnheyRhQ="
    file:
        - anki-iframe-viewer.zip
    skip_cleanup: true
    on:
        repo: rubyu/anki-iframe-viewer
        tags: true
        all_branches: true
